# Generated by Django 5.2.8 on 2026-02-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_course_m_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjct',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='project.course'),
        ),
    ]
