# Generated by Django 5.2.8 on 2026-02-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_subjct_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='project.subjct'),
            preserve_default=False,
        ),
    ]
