# Generated by Django 5.2.8 on 2026-02-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_test_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_track',
            name='chapter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='project.chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test_track',
            name='pass_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('runing', 'Runing'), ('fail', 'Fail')], default='runing', max_length=50),
        ),
    ]
