# Generated by Django 5.2.8 on 2026-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_test_track_chapter_alter_test_track_pass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test_track',
            name='correct_Q',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='test_track',
            name='total_Q',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
