# Generated by Django 5.2.8 on 2026-02-14 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_chapter_index_alter_test_track_correct_q_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='M_teacher',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'head_teacher'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
