# Generated by Django 5.2.8 on 2026-02-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_enrollment_student_alter_test_track_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('image', 'Image')], default=True, max_length=50),
            preserve_default=False,
        ),
    ]
