# Generated by Django 5.2.8 on 2026-02-17 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='project.chapter'),
        ),
    ]
