# Generated by Django 5.2.8 on 2026-02-18 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_topics_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjct',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
