# Generated by Django 5.2.8 on 2026-02-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_topics_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topics',
            name='checked',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
