# Generated by Django 5.2.8 on 2026-02-18 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_file_checked_alter_topics_checked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creater',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
