# Generated by Django 5.2.8 on 2026-02-18 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_file_creater'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creater',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Files', to=settings.AUTH_USER_MODEL),
        ),
    ]
