# Generated by Django 5.2.8 on 2026-02-20 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_file_creater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='Demo/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='Demo/')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo', to='project.subjct')),
            ],
        ),
    ]
