# Generated by Django 5.2.8 on 2026-02-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='demo',
            field=models.BooleanField(default=True),
        ),
    ]
