# Generated by Django 5.2.8 on 2026-02-21 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_topics_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='short/')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='project.file')),
            ],
        ),
    ]
