# Generated by Django 5.2.8 on 2026-05-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_alter_subjct_teacher_alter_subjct_total_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjct',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='project/'),
        ),
    ]
