# Generated by Django 5.2.8 on 2026-05-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_subjct_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='ch_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='project/'),
        ),
    ]
