# Generated by Django 5.2.8 on 2026-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_chapter_ch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_track',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
